### ISSUE TITLE
Question on sentiment output

### ISSUE THREAD

**Issue by ipheiman** [fhamborg/NewsMTSC#20]
Hi there authors, really impressive work with much ease to use, thanks for sharing this :)

I have a silly question regarding the template example provided:

- sentiment = tsc.infer_from_text("I like " ,"Peter", " but I don't like Robert.")
=> [{'class_id': 1, 'class_label': 'neutral', 'class_prob': 0.44148460030555725},
 {'class_id': 2, 'class_label': 'positive', 'class_prob': 0.4068439304828644},
 {'class_id': 0, 'class_label': 'negative', 'class_prob': 0.15167152881622314}]

In this case, why is the output neutral? I thought it should be positive. Just to clarify, the input should be [before target] [target] [after target]?

**Comment by junkgear** [comment]
Same doubt for me as well.
Sentiment for Peter (Target) should be positive.

**Comment by fhamborg** [comment]
> In this case, why is the output neutral? I thought it should be positive. 

As with all language models and other machine learning methods, the predictions will never be correct 100% of the time. As described in our paper, the model achieves an F1=82%.

> Just to clarify, the input should be [before target] [target] [after target]?

Yea, that's correct. 

As
