### ISSUE TITLE
A tutorial

### ISSUE THREAD

**Issue by asuerdem1** [fhamborg/NewsMTSC#27]
A tutorial about how to preprocess and prepare the data before passing sentiment analysis (for example, how to parse the sentence?) would be great. Otherwise, useless. Many thanks.

**Comment by fhamborg** [comment]
thanks for the report, but the goal of this repo is to provide a targeted sentiment classifier and respective datasets. please refer to other resources concerning how you preprocess your data. i suggest you start searching for named entity recognition, for example.

**Comment by asuerdem1** [comment]
Dear Felix,

I think there is a misunderstanding. Of course my question  is not about text preprocessing, I have no problem with that.
Let me put my question more clearly:
How do you segment the sentence for TSC? What is the logic? SRL? Clauses?
for example:

"I like " ,"Peter", " but I don't like Robert.")

What is the logic for segmenting the text this way?
Obviously, to be able to do the sentiment analysis, I need to segment the sentences, but I do not know the logic behind.
Some more info would be appreciated.
Thanks,
Ahmet
________________________________
