### ISSUE TITLE
sentencepiece metadata load failure

### ISSUE THREAD

**Issue by CodeAKrome** [fhamborg/NewsMTSC#28]
Made conda env for python 3.9
pip3 install NewsSentiment

Collecting sentencepiece==0.1.91 (from transformers<4,>=3.1.0->NewsSentiment)
  Using cached sentencepiece-0.1.91.tar.gz (500 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      Package sentencepiece was not found in the pkg-config search path.
      Perhaps you should add the directory containing `sentencepiece.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'sentencepiece', required by 'virtual:world', not found
      Failed to find sentencepiece pkgconfig
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by CodeAKrome** [comment]
Changed python to 3.8 and pip installs. This thing is very picky about the version.

Nevermind ... -- Emily LaTella

**Comment by fhamborg** [comment]
which OS?
