### ISSUE TITLE
cuda version not found

### ISSUE THREAD

**Issue by CodeAKrome** [fhamborg/NewsMTSC#29]
❯ python -V
Python 3.7.16
❯ pip3 -V
pip 22.3.1 from /home/kyle/anaconda3/envs/py37/lib/python3.7/site-packages/pip (python 3.7)
❯ pip3 install NewsSentiment[cuda]
zsh: no matches found: NewsSentiment[cuda]

This should be a right python version. No worries, I have the time, but there seems like some kinda packaging problem.
The non-cuda one works fine.

**Comment by fhamborg** [comment]
as the error message suggests, this is a zsh-related issue, should be fine if you use bash or - im not familiar with zsh - perhaps `pip3 install "NewsSentiment[cuda]"`
