### ISSUE TITLE
Add example

### ISSUE THREAD

**Issue by CodeAKrome** [fhamborg/NewsMTSC#30]
Excellent work. I was literally working on this very thing when I found this.
I wrote a short example program to explicitly show one way to use this.

**Comment by asuerdem1** [comment]
Hi [CodeAKrome] I am struggling to understand the logic for segmenting text around the target entity. I'd appreciate your example program, where can I have it?

**Comment by CodeAKrome** [comment]
Sorry for long response time. I need to find out how to get notifications for these types of events, or know where to look. Anyway, if you still need it. Good on ya for sticking with things. I wish you luck.

```python
import spacy
from transformers import AutoTokenizer, AutoModelForTokenClassification
from transformers import pipeline
from NewsSentiment import TargetSentimentClassifier

tokenizer = AutoTokenizer.from_pretrained("dslim/bert-large-NER")
model = AutoModelForTokenClassification.from_pretrained("dslim/bert-large-NER")
nlp = pipeline("ner", model=model, tokenizer=tokenizer)
TEXT = "On some great and glorious day the plain folks of the land will reach their heart's desire at last, and the White House will be adorned by a downright moron."
ner_spans = nlp(TEXT)
ents = [span["word"] for span in ner_spans]
print(f"Entities: {ents}")
tsc = TargetSentimentClassifier()
for span in ner_spans:
    l = TEXT[:span['start']]
    m = TEXT[span['start']:span['end']]
    r = TEXT[span['end']:]
    sentiment = tsc.infer_from_text(l, m, r)
    print(f"{span['entity']}\t{sentiment[0]['class_label']}\t{sentiment[0]['class_prob']:.2f}\t{m}")
```

**Comment by fhamborg** [comment]
added a link to your comment @CodeAKrome - thanks! this will be shown in the pypi readme once the next version is uploaded.

**Comment by fhamborg** [comment]
https://github.com/fhamborg/NewsMTSC/commit/0841bc7bba35676db1b94b3a464a86d9e4b61b40
