### ISSUE TITLE
NewsSentiment cuda] instal failing on dependency to cudatoolkit =10.1

### ISSUE THREAD

**Issue by networks1** [fhamborg/NewsMTSC#34]
Trying to install NewsSentiment[cuda] via pip3 in a fresh mamba environment with Python 3.8. This yields

`newssentiment[cuda] 1.1.25 depends on cudatoolkit==10.1; extra == "cuda"`

with that error repeated through versions down to newssentiment[cuda] 1.0.0 

If I install cudatoolkit=10.1 using conda, I get the same error. Is the [cuda] version known to be working and installable?

**Comment by fhamborg** [comment]
yep, cudatoolkit should be working fine. looks like an error related to cudatoolkit, so ill suggest to open an issue over there
