### ISSUE TITLE
Model update

### ISSUE THREAD

**Issue by yangheng95** [fhamborg/NewsMTSC#4]
Hi, I recent rework the LCF-BERT model, now it is much faster and stable. If you have interest to update the model, please see [PyABSA](https://github.com/yangheng95/PyABSA).

Cheers,

Yang Heng

**Comment by fhamborg** [comment]
Hi, this is interesting :-) Which of the models listed at https://github.com/yangheng95/PyABSA#model-support are you referring to? Is it still called LCF-BERT and thus this file? https://github.com/yangheng95/PyABSA/blob/release/pyabsa/module/apc/models/lcf_bert.py

**Comment by yangheng95** [comment]
I recommend to use fast-lcf-bert, which adopts an effcient lcf vec calculation method and use the global context features output to learn local cotnext features (means halfing the time every step).
