### ISSUE TITLE
How to deal with sentence with multiple target with GRUTSC?

### ISSUE THREAD

**Issue by Pager07** [fhamborg/NewsMTSC#7]
Hi @fhamborg,

I am sort of confused with the implementation on how to deal with sentences with multiple target using the GRUTSC model in training time. 

Do you end you making multiple inputs for the same sentence for each target?
eg. input1 = [cls,sentence,sep,target1,sep]
eg.  input2 = [cls,sentence,sep,target2,sep]
and so on..?

**Comment by fhamborg** [comment]
Thanks for your question! When using the grutsc model, the framework in this repo does exactly what you stated, i.e., it creates multiple training examples for such sentences. Note, though, that the framework supports further modes, too, e.g., if you implement your own model that supports multiple targets at the same time (you may want to check out the train.py and dataset.py files where - I think (I currently don't have PC access so cannot check it myself) - this functionality is implemented. Hope this helps!

**Comment by Pager07** [comment]
Thank you for your reply @fhamborg, that's very clear now. In your last paper (newtsc) you used a finetuned Bert on sentences randomly sampled from news articles from the Common Crawl News Crawl. Were the weights the finetuned Bert also used to get your results?
